import { ProductItem } from "@/types/store";

export const PRODUCTS: ProductItem[] = [
  {
    id: "prime-beef-boneless",
    name: "Prime Beef (100% Boneless)",
    yorubaName: "Eran Malu Pipe (Ail’egun)",
    category: "beef",
    description:
      "Artisanal hand-trimmed, pure lean muscle cuts sourced from healthy, grass-fed pasture cattle. Zero bone, zero gristle, maximum yield for rich Nigerian soups and gourmet feasts.",
    trustBadge: "Guaranteed 100% Boneless Pure Meat",
    isBonelessGuaranteed: true,
    isSpecialty: false,
    availableStates: ["Fresh", "Frozen"],
    tiers: [
      { weightLabel: "0.5kg (Half kg)", shortLabel: "0.5kg", subtitle: "Half kg", weightKg: 0.5, price: 3850 },
      { weightLabel: "1kg", shortLabel: "1kg", subtitle: "Standard", weightKg: 1, price: 7700 },
      { weightLabel: "2kg", shortLabel: "2kg", subtitle: "Family", weightKg: 2, price: 15400 },
      { weightLabel: "5kg", shortLabel: "5kg", subtitle: "Bulk Slab", weightKg: 5, price: 38500 },
      { weightLabel: "10kg", shortLabel: "10kg", subtitle: "Party Bag", weightKg: 10, price: 77000 },
    ],
    imageUrl: "/images/products/prime-beef-boneless.jpg",
    cutOptions: [
      "Medium Stew Chunks (Bite-sized)",
      "Large Party Cut (Ariya)",
      "Suya Strips (Thinly Sliced)",
      "Whole Muscle (Uncut Block)",
    ],
    unitLabel: "kg",
  },
  {
    id: "assorted-cow-intestines",
    name: "Assorted Cow Intestines (Inu Eran)",
    yorubaName: "Shaki, Edo, Abodi & Towel",
    category: "intestines",
    description:
      "Expertly sanitized and hygienically sorted prime offal medley: honeycomb tripe (shaki), tender liver (edo), abodi, and roundabouts. Pristine condition, zero off-flavors.",
    trustBadge: "Triple-Washed & Hygienic",
    isBonelessGuaranteed: false,
    isSpecialty: false,
    availableStates: ["Fresh", "Frozen"],
    tiers: [
      { weightLabel: "0.5kg (Half kg)", shortLabel: "0.5kg", subtitle: "Half kg", weightKg: 0.5, price: 3000 },
      { weightLabel: "1kg", shortLabel: "1kg", subtitle: "Standard", weightKg: 1, price: 6000 },
      { weightLabel: "2kg", shortLabel: "2kg", subtitle: "Family", weightKg: 2, price: 12000 },
      { weightLabel: "5kg", shortLabel: "5kg", subtitle: "Bulk Slab", weightKg: 5, price: 30000 },
    ],
    imageUrl: "/images/products/assorted-cow-intestines.jpg",
    cutOptions: [
      "Stew-Ready Assorted Pieces",
      "Pepper Soup Cut (Bite-sized)",
      "Whole Pre-washed Portions",
    ],
    unitLabel: "kg",
  },
  {
    id: "specialty-cow-head",
    name: "Whole / Split Cow Head (Ori Eran)",
    yorubaName: "Ori Eran (Singed & Cleaned)",
    category: "specialty",
    description:
      "Entire or split prime cow head, traditional firewood singed and scrubbed spotless. Includes rich tender cheeks, succulent tongue, and gelatinous delicacies for authentic ceremonies.",
    trustBadge: "Hand-Singed & Pressure Scrubbed",
    isBonelessGuaranteed: false,
    isSpecialty: true,
    baseStartingPrice: 50000,
    availableStates: ["Fresh"],
    imageUrl: "/images/products/specialty-cow-head.jpg",
    cutOptions: [
      "Chopped into Stew Chunks with Bone",
      "Split in Half (Bilateral)",
      "Whole Head (Singed & Washed)",
    ],
    unitLabel: "Unit",
  },
  {
    id: "specialty-cow-tail",
    name: "Prime Cow Tail (Iru Eran / Oxtail)",
    yorubaName: "Iru Eran (Pure Oxtail Medallions)",
    category: "specialty",
    description:
      "Deeply marbled, gelatin-dense whole prime oxtail. Sliced into thick artisanal round medallions upon request. Supreme richness for luxury Nigerian stews, oxtail pepper soup, and braises.",
    trustBadge: "Prime Selected Tail",
    isBonelessGuaranteed: false,
    isSpecialty: true,
    baseStartingPrice: 15000,
    availableStates: ["Fresh"],
    imageUrl: "/images/products/specialty-cow-tail.jpg",
    cutOptions: [
      "Neat Medallion Discs (Joint Sliced)",
      "Whole Tail Intact",
    ],
    unitLabel: "Unit",
  },
  {
    id: "specialty-cow-leg",
    name: "Cow Leg (Bokoto)",
    yorubaName: "Bokoto / Trotters (Singed & Cleaned)",
    category: "specialty",
    description:
      "Collagen-dense, golden-singed cow feet meticulously cleaned and tenderized. The undisputed crown jewel for authentic Nigerian pepper soup and party tomato stew.",
    trustBadge: "Flame-Singed & Clean",
    isBonelessGuaranteed: false,
    isSpecialty: true,
    baseStartingPrice: 6000,
    availableStates: ["Fresh"],
    imageUrl: "/images/products/specialty-cow-leg.jpg",
    cutOptions: [
      "Chopped into Bite Chunks",
      "Halved Crosswise",
      "Whole Leg Cleaned",
    ],
    unitLabel: "Unit",
  },
  {
    id: "goat-meat-ogufe",
    name: "Goat Meat (Ogufe)",
    yorubaName: "Eran Ewure / Ogufe Prime Share",
    category: "goat",
    description:
      "Premium mature castrated billy goat meat (Ogufe) renowned for unmatched aroma, tenderness, and taste. Sold in measured community slots containing balanced ribs, leg, and loin portions.",
    trustBadge: "Traditional Ogufe Flavor",
    isBonelessGuaranteed: false,
    isSpecialty: false,
    availableStates: ["Fresh", "Frozen"],
    tiers: [
      { weightLabel: "1 Slot (Share)", shortLabel: "1 Slot", subtitle: "Standard Share", slots: 1, price: 25000 },
      { weightLabel: "2 Slots (Half Goat)", shortLabel: "2 Slots", subtitle: "Half Goat", slots: 2, price: 50000 },
      { weightLabel: "4 Slots (Full Goat)", shortLabel: "4 Slots", subtitle: "Full Goat", slots: 4, price: 100000 },
    ],
    imageUrl: "/images/products/goat-meat-ogufe.jpg",
    cutOptions: [
      "Classic Asun Chunks (Bite-sized with skin)",
      "Party Stew Chunks",
      "Pepper Soup Chunks",
      "Whole Primal Parts",
    ],
    unitLabel: "Slot",
  },
];
