import { DeliveryZone } from "@/types/store";

export const DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: "pickup-adigbe",
    name: "Self-Pickup (Adigbe Store)",
    area: "God's Hope Hospital Car Park, Adigbe",
    fee: 0,
    estimatedTime: "Frozen always in-store (Mon–Sat 8am–7pm, Sun 1pm–7pm); Fresh on Fridays by 12:00 Noon",
    isPickup: true,
  },
  {
    id: "zone-adigbe",
    name: "Adigbe & Environs",
    area: "Adigbe, Obada Road, Harmony, Elite Road",
    fee: 1000,
    estimatedTime: "Same-Day Delivery (9:00 AM - 12:00 PM)",
    isPickup: false,
  },
  {
    id: "zone-ibara",
    name: "Ibara & GRA",
    area: "Ibara GRA, Omida, Ibara Housing Estate, Lalubu Street",
    fee: 1500,
    estimatedTime: "Same-Day Delivery (10:00 AM - 1:00 PM)",
    isPickup: false,
  },
  {
    id: "zone-oke-mosan",
    name: "Oke-Mosan",
    area: "State Secretariat, Governor's Office, Olusegun Obasanjo Presidential Library (OOPL)",
    fee: 2000,
    estimatedTime: "Same-Day Delivery (11:00 AM - 2:00 PM)",
    isPickup: false,
  },
  {
    id: "zone-kuto",
    name: "Kuto & Isabo",
    area: "Kuto Market axis, Isabo, High Court, Quarry Road",
    fee: 1500,
    estimatedTime: "Same-Day Delivery (10:30 AM - 1:30 PM)",
    isPickup: false,
  },
  {
    id: "zone-idi-aba",
    name: "Idi-Aba",
    area: "Federal Medical Centre (FMC), Idi-Aba, Ajebo Road",
    fee: 2000,
    estimatedTime: "Same-Day Delivery (11:00 AM - 2:30 PM)",
    isPickup: false,
  },
  {
    id: "zone-camp",
    name: "Camp & FUNAAB Axis",
    area: "Camp Junction, Federal University of Agriculture (FUNAAB), Alabata Axis",
    fee: 2500,
    estimatedTime: "Same-Day Delivery (12:00 PM - 3:30 PM)",
    isPickup: false,
  },
  {
    id: "zone-obantoko",
    name: "Obantoko & Asero",
    area: "Obantoko, Asero, Somorin, Ibadan Road Axis",
    fee: 2500,
    estimatedTime: "Same-Day Delivery (12:00 PM - 3:30 PM)",
    isPickup: false,
  },
  {
    id: "zone-lafenwa",
    name: "Lafenwa & Ita-Oshin",
    area: "Lafenwa, Rounder, Ita-Oshin, Ayetoro Road Axis",
    fee: 2000,
    estimatedTime: "Same-Day Delivery (11:30 AM - 2:30 PM)",
    isPickup: false,
  },
];
